/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CertificateRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "certificates" | "getCertificate" | "storeCertificate"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CertificateStored"): EventFragment;

  encodeFunctionData(
    functionFragment: "certificates",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "storeCertificate",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "certificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeCertificate",
    data: BytesLike
  ): Result;
}

export namespace CertificateStoredEvent {
  export type InputTuple = [certificateId: string, certificateHash: string];
  export type OutputTuple = [certificateId: string, certificateHash: string];
  export interface OutputObject {
    certificateId: string;
    certificateHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CertificateRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CertificateRegistry;
  waitForDeployment(): Promise<this>;

  interface: CertificateRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  certificates: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        certificateHash: string;
        signature: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getCertificate: TypedContractMethod<
    [_certificateId: string],
    [[string, string, bigint]],
    "view"
  >;

  storeCertificate: TypedContractMethod<
    [_certificateId: string, _certificateHash: string, _signature: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "certificates"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, boolean] & {
        certificateHash: string;
        signature: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCertificate"
  ): TypedContractMethod<
    [_certificateId: string],
    [[string, string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "storeCertificate"
  ): TypedContractMethod<
    [_certificateId: string, _certificateHash: string, _signature: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CertificateStored"
  ): TypedContractEvent<
    CertificateStoredEvent.InputTuple,
    CertificateStoredEvent.OutputTuple,
    CertificateStoredEvent.OutputObject
  >;

  filters: {
    "CertificateStored(string,string)": TypedContractEvent<
      CertificateStoredEvent.InputTuple,
      CertificateStoredEvent.OutputTuple,
      CertificateStoredEvent.OutputObject
    >;
    CertificateStored: TypedContractEvent<
      CertificateStoredEvent.InputTuple,
      CertificateStoredEvent.OutputTuple,
      CertificateStoredEvent.OutputObject
    >;
  };
}
