import React, { useState } from 'react';
import '../styles/AdminAuth.css'; // Importing the external CSS

const AdminAuth = () => {
  // State to toggle between Login and Register views
  const [isLogin, setIsLogin] = useState(true);

  // Single state object for all form data
  const [formData, setFormData] = useState({
    username: '',
    email: '',
    password: '',
    walletaddress: '',
    role: 'Support' // Default role
  });

  // Handle Input Change
  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  // Handle Form Submission
  const handleSubmit = (e) => {
    e.preventDefault();
    
    if (isLogin) {
      console.log("Logging in with:", { 
        email: formData.email, 
        password: formData.password 
      });
      // TODO: Call Login API
    } else {
      console.log("Registering new admin:", formData);
      // TODO: Call Register API (admin_id will be generated by backend)
    }
  };

  // Reset form when toggling modes
  const toggleMode = () => {
    setIsLogin(!isLogin);
    setFormData({
      username: '',
      email: '',
      password: '',
      walletaddress: '',
      role: 'Support'
    });
  };

  return (
    <div className="auth-page-container">
      <div className="auth-card">
        <div className="auth-header">
          <h2>CertiNexa <span className="highlight">Admin</span></h2>
          <p>{isLogin ? 'Secure Access Portal' : 'Onboard New Administrator'}</p>
        </div>

        <form onSubmit={handleSubmit}>
          
          {/* Fields for Registration ONLY */}
          {!isLogin && (
            <>
              <div className="form-group">
                <label>Username</label>
                <input
                  type="text"
                  name="username"
                  className="form-input"
                  placeholder="Enter admin username"
                  value={formData.username}
                  onChange={handleChange}
                  required
                />
              </div>
            </>
          )}

          {/* Fields for Both Login and Registration */}
          <div className="form-group">
            <label>Email Address</label>
            <input
              type="email"
              name="email"
              className="form-input"
              placeholder="admin@certinexa.com"
              value={formData.email}
              onChange={handleChange}
              required
            />
          </div>

          <div className="form-group">
            <label>Password</label>
            <input
              type="password"
              name="password"
              className="form-input"
              placeholder="••••••••"
              value={formData.password}
              onChange={handleChange}
              required
            />
          </div>

          {/* Fields for Registration ONLY */}
          {!isLogin && (
            <>
              <div className="form-group">
                <label>Wallet Address (Blockchain)</label>
                <input
                  type="text"
                  name="walletaddress"
                  // "wallet-field" class adds the Chain Teal border
                  className="form-input wallet-field" 
                  placeholder="0x..."
                  value={formData.walletaddress}
                  onChange={handleChange}
                  required
                />
              </div>

              <div className="form-group">
                <label>Role</label>
                <select
                  name="role"
                  className="form-input"
                  value={formData.role}
                  onChange={handleChange}
                >
                  <option value="Support">Support</option>
                  <option value="SuperAdmin">SuperAdmin</option>
                </select>
              </div>
            </>
          )}

          <button type="submit" className="auth-btn">
            {isLogin ? 'Login to Dashboard' : 'Register Admin'}
          </button>
        </form>

        <div className="toggle-text">
          {isLogin ? "New to the team?" : "Already have an account?"}
          <span onClick={toggleMode} className="toggle-link">
            {isLogin ? "Create ID" : "Login Here"}
          </span>
        </div>
      </div>
    </div>
  );
};

export default AdminAuth;